title: AromaBite
description: AromaBite: An Edible Retronasal Olfactory Release Library
theme: just-the-docs

url: https://jingruchenmax.github.io/AromaBite

aux_links:
  Template Repository: https://github.com/jingruchenmax/AromaBite
