title: AromaBite
description: AromaBite - An Edible Retronasal Olfactory Release Library
theme: just-the-docs

url: https://aromabite.github.io

aux_links:
  Template Repository: https://github.com/AromaBite
